/costmap/costmap:
  ros__parameters:
    always_send_full_costmap: true
    clearable_layers:
    - obstacle_layer
    - voxel_layer
    footprint: '[[-1.0, -1.0], [-1.0, 1.0], [1.0, 1.0], [2.5, 0.0], [1.0, -1.0]]'
    footprint_padding: 1.0
    global_frame: ego_vehicle
    height: 20
    inflation_layer:
      cost_scaling_factor: 1.0
      enabled: true
      inflate_around_unknown: true
      inflate_unknown: false
      inflation_radius: 0.55
      plugin: nav2_costmap_2d::InflationLayer
    lethal_cost_threshold: 100
    map_topic: /map
    observation_sources: ''
    obstacle_layer:
      combination_method: 1
      enabled: true
      footprint_clearing_enabled: true
      max_obstacle_height: 100.0
      observation_sources: pointcloud
      plugin: nav2_costmap_2d::ObstacleLayer
      pointcloud:
        clearing: true
        data_type: PointCloud2
        expected_update_rate: 0.0
        inf_is_valid: false
        marking: true
        max_obstacle_height: 100.0
        min_obstacle_height: 0.5
        observation_persistence: 0.0
        obstacle_range: 2.5
        raytrace_range: 3.0
        sensor_frame: ''
        topic: /carla/ego_vehicle/center_lidar
    origin_x: 0.0
    origin_y: 0.0
    plugins:
    - obstacle_layer
    - voxel_layer
    - inflation_layer
    publish_frequency: 30.0
    resolution: 0.5
    robot_base_frame: ego_vehicle
    robot_radius: 0.1
    rolling_window: true
    track_unknown_space: false
    transform_tolerance: 0.3
    trinary_costmap: false
    unknown_cost_value: 255
    update_frequency: 30.0
    use_maximum: false
    use_sim_time: true
    voxel_layer:
      combination_method: 1
      enabled: true
      footprint_clearing_enabled: true
      mark_threshold: 2
      max_obstacle_height: 100.0
      observation_sources: pointcloud
      origin_z: 0.0
      plugin: nav2_costmap_2d::VoxelLayer
      publish_voxel_map: true
      unknown_threshold: 1
      z_resolution: 0.2
      z_voxels: 16
      pointcloud:
        clearing: true
        data_type: PointCloud2
        expected_update_rate: 0.0
        inf_is_valid: false
        marking: true
        max_obstacle_height: 100.0
        min_obstacle_height: 0.5
        observation_persistence: 0.0
        obstacle_range: 200.0
        raytrace_range: 200.0
        sensor_frame: ''
        topic: /carla/ego_vehicle/center_lidar
        publish_voxel_map: true
        

    width: 50
