/local_planner/trajectory/generator:
  ros__parameters:
    A_star_algo:
      allow_unknown: true
      analytic_expansion_ratio: 2.0
      angle_quantization_bins: 72
      change_penalty: 0.5
      cost_penalty: 1.2
      downsampling_factor: 1
      max_iterations: -1
      max_planning_time_ms: 5000.0
      minimum_turning_radius: 0.2
      motion_model_for_search: DUBIN
      non_straight_penalty: 1.05
      reverse_penalty: 2.0
      smooth_path: false
      tolerance: 0.125
    debug: false
    use_sim_time: false
