/septentrio_gnss_driver:
  ros__parameters:
    activate_debug_log: false
    ant_aux1_serial_nr: Unknown
    ant_aux1_type: Unknown
    ant_serial_nr: Unknown
    ant_type: Unknown
    att_offset:
      heading: 0.0
      pitch: 0.0
    aux1_frame_id: aux1
    datum: Default
    device: tcp://192.168.3.1:28784
    frame_id: gnss
    get_spatial_config_from_tf: false
    imu_frame_id: imu
    ins_initial_heading: auto
    ins_spatial_config:
      ant_lever_arm:
        x: 0.0
        y: 0.0
        z: 0.0
      imu_orientation:
        theta_x: 0.0
        theta_y: 0.0
        theta_z: 0.0
      poi_lever_arm:
        delta_x: 0.0
        delta_y: 0.0
        delta_z: 0.0
      vsm_lever_arm:
        vsm_x: 0.0
        vsm_y: 0.0
        vsm_z: 0.0
    ins_std_dev_mask:
      att_std_dev: 5.0
      pos_std_dev: 10.0
    ins_use_poi: false
    insert_local_frame: false
    leap_seconds: -128
    local_frame_id: odom
    lock_utm_zone: true
    login:
      password: ''
      user: ''
    multi_antenna: true
    ntrip_settings:
      caster: ''
      mode: ''
      rx_has_internet: false
      rx_input_corrections_serial: ''
      rx_input_corrections_tcp: 0
    poi_frame_id: base_link
    poi_to_arp:
      delta_e: 0.0
      delta_n: 0.0
      delta_u: 0.0
    polling_period:
      pvt: 0
      rest: 500
    publish:
      attcoveuler: true
      atteuler: true
      basevectorcart: false
      basevectorgeod: false
      diagnostics: false
      exteventinsnavcart: false
      exteventinsnavgeod: false
      extsensormeas: false
      gpgga: false
      gpgsa: false
      gpgsv: false
      gprmc: false
      gpsfix: true
      gpst: false
      imu: false
      imusetup: false
      insnavcart: false
      insnavgeod: false
      localization: false
      measepoch: false
      navsatfix: false
      poscovcartesian: false
      poscovgeodetic: true
      pose: false
      pvtcartesian: false
      pvtgeodetic: true
      tf: false
      twist: false
      velcovgeodetic: true
      velsensorsetup: false
    receiver_type: gnss
    rtk_settings:
      ip_server_1:
        id: ''
      ip_server_2:
        id: ''
      ip_server_3:
        id: ''
      ip_server_4:
        id: ''
      ip_server_5:
        id: ''
      ntrip_1:
        id: ''
      ntrip_2:
        id: ''
      ntrip_3:
        id: ''
      serial_1:
        port: ''
      serial_2:
        port: ''
      serial_3:
        port: ''
      serial_4:
        port: ''
      serial_5:
        port: ''
    serial:
      baudrate: 921600
      hw_flow_control: 'off'
      rx_serial_port: USB1
    use_gnss_time: false
    use_ros_axis_orientation: true
    use_sim_time: false
    vehicle_frame_id: base_link
    vsm_frame_id: vsm
