costmap:
  costmap:
    ros__parameters:
      always_send_full_costmap: false
      footprint_padding: 1.0
      footprint: "[[-1.0, -1.0], [-1.0, 1.0], [1.0, 1.0], [2.5, 0.0], [1.0, -1.0]]"
      global_frame: ego_vehicle
      height: 500
      width: 500
      origin_x: -500.0
      origin_y: -500.0
      lethal_cost_threshold: 100
      # map_topic
      publish_frequency: 30.0
      update_frequency: 30.0
      resolution: 0.5
      robot_base_frame: ego_vehicle
      use_sim_time: true
      plugins: ["obstacle_layer", "voxel_layer", "inflation_layer"]
      track_unknown_space: true
      rolling_window: true
      trinary_costmap: false
      use_maximum: true

      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        footprint_clearing_enabled: true
        max_obstacle_height: 100.0
        publish_voxel_map: true
        origin_z: 0.0
        z_resolution: 0.2
        z_voxels: 16
        unknown_threshold: 15
        mark_threshold: 0
        observation_sources: pointcloud
        combination_method: 1
        pointcloud:  # no frame set, uses frame from message
          topic: /carla/ego_vehicle/center_lidar
          max_obstacle_height: 100.0
          min_obstacle_height: 0.5
          obstacle_max_range: 100.0
          obstacle_min_range: 0.0
          obstacle_range: 200.0
          raytrace_range: 200.0
          raytrace_max_range: 300
          raytrace_min_range: 0.0
          clearing: true
          marking: true
          data_type: "PointCloud2"
          observation_persistence: 0.0

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: pointcloud
        footprint_clearing_enabled: true
        max_obstacle_height: 100.0
        combination_method: 1
        pointcloud:
          topic: /carla/ego_vehicle/center_lidar
          obstacle_max_range: 100.0
          obstacle_min_range: 0.0
          raytrace_max_range: 100.0
          raytrace_min_range: 0.0
          max_obstacle_height: 100.0
          min_obstacle_height: 0.5
          clearing: True
          marking: True
          data_type: "PointCloud2"
          inf_is_valid: false
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.55
        cost_scaling_factor: 1.0
        inflate_unknown: false
        inflate_around_unknown: true


